
on: [push,workflow_dispatch]
name: variable substitution in json


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/variable-substitution@v1 
      with:
          files: 'employee.json'
      env:
          username: tcranz
          password: ${{ secrets.PASSWORD }}
          url: https://github.com/${{github.repository}}

    - run: cat employee.json
      # echo ${{ env.last-name }}
      # echo ${{ env.username }}
      # echo ${{ env.password }}
      # echo ${{ env.url }}
